Build script for MacOS Intel

diff --git a/.github/workflows/build_multiplatform.yml b/.github/workflows/build_multiplatform.yml
--- a/.github/workflows/build_multiplatform.yml
+++ b/.github/workflows/build_multiplatform.yml
@@ -134,3 +134,99 @@ jobs:
         with:
           name: mac-debug-artifact
           path: build/debug/libVulVoxOptimizationProject.a
+
+  release-macOS_Intel:
+    runs-on: macos-13
+    name: Build on MacOS-13
+    env:
+      VULKAN_SDK_VERSION: ""
+      VULKAN_SDK_INSTALLER: ""
+      VERSION_URL: "https://vulkan.lunarg.com/sdk/latest/mac.txt"
+      SDK_URL: ""
+    steps:
+      #checkout code
+      - name: Checkout code
+        id: checkout_code
+        uses: actions/checkout@v4
+
+      #Setup Vulkan SDK
+      - name: Check Vulkan SDK Version
+        shell: bash
+        run: |
+          echo "retrieving latest version from url: $VERSION_URL"
+          VULKAN_SDK_VERSION=$(curl -sL $VERSION_URL)
+          echo "latest version for MacOS is: $VULKAN_SDK_VERSION"
+          echo "VULKAN_SDK_VERSION=$VULKAN_SDK_VERSION" >> $GITHUB_ENV
+
+      - name: Download and unzip Vulkan SDK
+        shell: bash
+        run: |
+            VULKAN_SDK_VERSION=${{env.VULKAN_SDK_VERSION}}
+            VERSION_URL=${{env.VERSION_URL}}
+            VULKAN_SDK_INSTALLER=$PWD/VULKAN_SDK_INSTALLER
+            echo "VULKAN_SDK_INSTALLER=$VULKAN_SDK_INSTALLER" >> $GITHUB_ENV
+            SDK_URL="https://sdk.lunarg.com/sdk/download/$VULKAN_SDK_VERSION/mac/vulkan_sdk.dmg?Human=true"
+            echo "SDK_URL=$SDK_URL" >> $GITHUB_ENV
+            echo "Downloading Vulkan SDK $VULKAN_SDK_VERSION from $SDK_URL"
+            curl --fail-with-body -s -L -o vulkan_sdk.zip $SDK_URL || { echo "curl failed with error code: $?" >&2 ; curl -s -L --head $VERSION_URL >&2 ; exit 32 ; }
+            test -f vulkan_sdk.zip
+            ls -lh vulkan_sdk.zip >&2
+            echo "Unzipping Vulkan SDK into $VULKAN_SDK_INSTALLER"
+            mkdir -p "$VULKAN_SDK_INSTALLER"
+            unzip -q vulkan_sdk.zip -d "$VULKAN_SDK_INSTALLER"
+            ls -lh "$VULKAN_SDK_INSTALLER" >&2
+            du -hs $VULKAN_SDK_INSTALLER
+            
+      - name: Install Vulkan SDK
+        shell: bash
+        run: |
+          VULKAN_SDK_INSTALLER=${{env.VULKAN_SDK_INSTALLER}}
+          VULKAN_SDK=$PWD/VULKAN_SDK
+          echo "Installing from unzipped folder: $VULKAN_SDK_INSTALLER"
+          sudo $VULKAN_SDK_INSTALLER/InstallVulkan.app/Contents/MacOS/InstallVulkan --root "$VULKAN_SDK" --accept-licenses --default-answer --confirm-command install
+          echo "Cleaning installer files"
+          sudo rm -rf "$VULKAN_SDK_INSTALLER"
+          #Check install
+          if [ ! -d "$VULKAN_SDK" ]; then
+          echo "Error: Vulkan SDK installation failed." >&2
+          exit 1
+          fi
+          #ls -h $VULKAN_SDK
+          cd $VULKAN_SDK
+          sudo ./install_vulkan.py
+          
+      - name: Install glfw
+        run: brew install glfw
+      
+      - name: Create build directory (release)
+        run: cmake -S VulVoxOptimizationProject/ -B build/release/ -D CMAKE_BUILD_TYPE=Release
+
+      - name: Build project (release)
+        run: cmake --build build/release/ --config Release
+
+      - name: Create build directory (debug)
+        run: cmake -S VulVoxOptimizationProject/ -B build/debug/ -D CMAKE_BUILD_TYPE=Debug
+
+      - name: Build project (debug)
+        run: cmake --build build/debug/ --config Debug
+
+      - name: List files in release directory
+        run: ls build/release/
+
+      - name: List files in debug directory
+        run: ls build/debug/
+
+      - name: List files in build directory
+        run: ls build/
+
+      #Upload release build as artifact
+      - uses: actions/upload-artifact@v4
+        with:
+          name: mac-release-artifact_intel
+          path: build/release/libVulVoxOptimizationProject.a
+          
+      #Upload release build as artifact
+      - uses: actions/upload-artifact@v4
+        with:
+          name: mac-debug-artifact_intel
+          path: build/debug/libVulVoxOptimizationProject.a
