Update build_multiplatform.yml
Turns out the new SDK is a zip.. should work now?

diff --git a/.github/workflows/build_multiplatform.yml b/.github/workflows/build_multiplatform.yml
--- a/.github/workflows/build_multiplatform.yml
+++ b/.github/workflows/build_multiplatform.yml
@@ -44,7 +44,7 @@ jobs:
     name: Build on MacOS-latest
     env:
       VULKAN_SDK_VERSION: ""
-      VULKAN_SDK: ""
+      VULKAN_SDK_INSTALLER: ""
       VERSION_URL: "https://vulkan.lunarg.com/sdk/latest/mac.txt"
       SDK_URL: ""
     steps:
@@ -61,33 +61,36 @@ jobs:
           VULKAN_SDK_VERSION=$(curl -sL $VERSION_URL)
           echo "latest version for MacOS is: $VULKAN_SDK_VERSION"
           basedir=$PWD
-          echo "VULKAN_SDK=-$basedir/VULKAN_SDK" >> $GITHUB_ENV
           echo "VULKAN_SDK_VERSION=$VULKAN_SDK_VERSION" >> $GITHUB_ENV
 
-      - name: Download Vulkan SDK
+      - name: Download and unzip Vulkan SDK
         shell: bash
         run: |
             VULKAN_SDK_VERSION=${{env.VULKAN_SDK_VERSION}}
             VERSION_URL=${{env.VERSION_URL}}
+            VULKAN_SDK_INSTALLER=-$basedir/VULKAN_SDK_INSTALLER
+            echo "VULKAN_SDK_INSTALLER=$VULKAN_SDK_INSTALLER" >> $GITHUB_ENV
             SDK_URL="https://sdk.lunarg.com/sdk/download/$VULKAN_SDK_VERSION/mac/vulkan_sdk.dmg?Human=true"
             echo "SDK_URL=$SDK_URL" >> $GITHUB_ENV
             echo "Downloading Vulkan SDK $VULKAN_SDK_VERSION from $SDK_URL"
-            curl --fail-with-body -s -L -o vulkan_sdk.dmg.tmp $SDK_URL || { echo "curl failed with error code: $?" >&2 ; curl -s -L --head $VERSION_URL >&2 ; exit 32 ; }
-            test -f vulkan_sdk.dmg.tmp
-            mv -v vulkan_sdk.dmg.tmp vulkan_sdk.dmg
-            ls -lh vulkan_sdk.dmg >&2
-
+            curl --fail-with-body -s -L -o vulkan_sdk.zip $SDK_URL || { echo "curl failed with error code: $?" >&2 ; curl -s -L --head $VERSION_URL >&2 ; exit 32 ; }
+            test -f vulkan_sdk.zip
+            ls -lh vulkan_sdk.zip >&2
+            echo "Unzipping Vulkan SDK"
+            unzip -q vulkan_sdk.zip -d "$VULKAN_SDK_INSTALLER"
+            ls -lh "$VULKAN_SDK_INSTALLER" >&2
+            du -hs $VULKAN_SDK_INSTALLER
+            
       - name: Install Vulkan SDK
         shell: bash
         run: |
-          VULKAN_SDK=${{env.VULKAN_SDK}}
-          echo $(test -d $VULKAN_SDK && test -f vulkan_sdk.dmg)
-          file vulkan_sdk.dmg
-          MOUNTPOINT=$(hdiutil attach vulkan_sdk.dmg -verbose | grep -i vulkansdk | awk 'END {print $NF}')
-          echo "Installing from mountpoint: $MOUNTPOINT"
-          sudo $MOUNTPOINT/InstallVulkan.app/Contents/MacOS/InstallVulkan --root "$VULKAN_SDK" --accept-licenses --default-answer --confirm-command install
-          du -hs $VULKAN_SDK
-
+          VULKAN_SDK_INSTALLER=${{env.VULKAN_SDK_INSTALLER}}
+          VULKAN_SDK=-$basedir/VULKAN_SDK
+          echo "Installing from unzipped folder: $VULKAN_SDK_INSTALLER"
+          sudo $VULKAN_SDK/InstallVulkan.app/Contents/MacOS/InstallVulkan --root "$sdk_temp" --accept-licenses --default-answer --confirm-command install
+          echo "Cleaning installer files"
+          sudo rm -rf "VULKAN_SDK_INSTALLER"
+          
       - name: Install glfw
         run: brew install glfw
       
