Action: Vulkan SDK URL update

diff --git a/.github/workflows/build_multiplatform.yml b/.github/workflows/build_multiplatform.yml
--- a/.github/workflows/build_multiplatform.yml
+++ b/.github/workflows/build_multiplatform.yml
@@ -65,8 +65,9 @@ jobs:
       - name: Download Vulkan SDK
         shell: bash
         run: |
-            #https://sdk.lunarg.com/sdk/download/$VULKAN_SDK_VERSION/$os/$filename?Human=true
-            curl --fail-with-body -s -L -o vulkan_sdk.dmg.tmp $VERSION_URL || { echo "curl failed with error code: $?" >&2 ; curl -s -L --head $VERSION_URL >&2 ; exit 32 ; }
+            SDK_URL=$(https://sdk.lunarg.com/sdk/download/$VULKAN_SDK_VERSION/mac/vulkan_sdk.dmg?Human=true)
+            echo "Downloading Vulkan SDK $VULKAN_SDK_VERSION from $SDK_URL"
+            curl --fail-with-body -s -L -o vulkan_sdk.dmg.tmp $SDK_URL || { echo "curl failed with error code: $?" >&2 ; curl -s -L --head $VERSION_URL >&2 ; exit 32 ; }
             test -f ${filename}.tmp
             mv -v ${filename}.tmp ${filename} 
             ls -lh $filename >&2
