Update build_multiplatform.yml

diff --git a/.github/workflows/build_multiplatform.yml b/.github/workflows/build_multiplatform.yml
--- a/.github/workflows/build_multiplatform.yml
+++ b/.github/workflows/build_multiplatform.yml
@@ -72,7 +72,7 @@ jobs:
             VERSION_URL= ${{env.VERSION_URL}}
             echo "SDK_URL=$SDK_URL" >> $GITHUB_ENV
             echo "Downloading Vulkan SDK $VULKAN_SDK_VERSION from $SDK_URL"
-            curl --fail-with-body -s -L -o vulkan_sdk.dmg $SDK_URL || { echo "curl failed with error code: $?" >&2 ; curl -s -L --head $VERSION_URL >&2 ; exit 32 ; }
+            curl --fail-with-body -s -L -o vulkan_sdk.dmg.tmp $SDK_URL || { echo "curl failed with error code: $?" >&2 ; curl -s -L --head $VERSION_URL >&2 ; exit 32 ; }
             test -f vulkan_sdk.dmg.tmp
             mv -v vulkan_sdk.dmg.tmp vulkan_sdk.dmg
             ls -lh vulkan_sdk.dmg >&2
